# Generated by Django 4.2.20 on 2025-03-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageRide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
