# Generated by Django 4.2.20 on 2025-03-26 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageRide', '0004_alter_ridemodel_id_driver_alter_ridemodel_id_rider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridemodel',
            name='id_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rides_as_driver', to=settings.AUTH_USER_MODEL),
        ),
    ]
